services:
  redis:
    build: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - wallet_network
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - wallet_network

  contextEnrichment:
    build: ./contextEnrichment
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - wallet_network

  llmService:
    build: ./llmService
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MODEL_PATH=/app/models/phi-3-mini.gguf
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        limits:
          memory: 3G

    depends_on:
      - redis
    networks:
      - wallet_network

  merchantService:
    build: ./merchantService
    ports:
      - "8003:8003"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - wallet_network

networks:
  wallet_network:
    driver: bridge


