FROM python:3.10-slim
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN mkdir -p /app/models
EXPOSE 8002
CMD ["uvicorn", "main:app", "--reload", "--port", "8002"]
