from .models import ArtemisUser, ArtemisMerchant
from django.shortcuts import get_object_or_404
from ninja.errors import HttpError
from ninja import NinjaAPI
import uuid
import json
import os
import redis

from .schema import InputSchema, mercSchema, RoleSchema
from .auth import CustomAuth

try:
    from google.cloud import pubsub_v1
    cred = os.getenv("cred")
    if cred:
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = cred
    publisher = pubsub_v1.PublisherClient()
except Exception as e:
    print(f"Warning: PubSub unavailable: {e}")
    publisher = None

INPUT_TOPIC = os.getenv("INPUT_TOPIC")
MERCHANT_TOPIC = os.getenv("MERCHANT_TOPIC")

# Redis client for offer result polling (FIX: added missing GET /offers endpoint)
_redis_host = os.getenv("REDIS_HOST", "localhost")
_redis_port = int(os.getenv("REDIS_PORT", 6379))
try:
    redis_client = redis.Redis(host=_redis_host, port=_redis_port, decode_responses=True)
    redis_client.ping()
except Exception as e:
    print(f"Warning: Redis unavailable: {e}")
    redis_client = None

api = NinjaAPI()


def _publish(topic: str, data: dict):
    """Safe publish — no-op if publisher not configured."""
    if not publisher or not topic:
        print(f"PubSub not configured — would publish to {topic}: {data}")
        return None
    encoded = json.dumps(data).encode("utf-8")
    future = publisher.publish(topic, encoded)
    return future.result()


@api.get("/health")
def health_check(request):
    return {"status": "OK"}


@api.get("/me", auth=CustomAuth())
def get_me(request):
    user = request.auth
    return {
        "email": user.email,
        "role": user.role,
        "google_id": user.google_id,
    }


@api.post("/role-decider", auth=CustomAuth())
def role_choose(request, payload: RoleSchema):
    user = request.auth
    role = payload.role
    if role not in ["user", "merchant"]:
        raise HttpError(400, "Invalid role — must be 'user' or 'merchant'")
    art = get_object_or_404(ArtemisUser, email=user.email)
    if art.role:
        raise HttpError(400, "Role already assigned")
    art.role = role
    art.save()
    return {"message": "role assigned successfully", "role": role}


@api.post("/trigger", auth=CustomAuth())
def trig(request, payload: InputSchema):
    user = request.auth
    if user.role != "user":
        raise HttpError(403, "Only users can trigger offers")

    task_id = str(uuid.uuid4())
    dt = {
        "task_id": task_id,
        "intent_token": payload.intent_token,
        "geo_zone": payload.geo_zone,
        "timestamp": payload.timestamp or None,
    }

    result = _publish(INPUT_TOPIC, dt)
    return {
        "status": f"published",
        "task_id": task_id,
        "pubsub_id": str(result) if result else "local-dev",
    }


# FIX: This endpoint was completely missing — frontend polls /offers/{task_id} for results
@api.get("/offers/{task_id}", auth=CustomAuth())
def get_offer(request, task_id: str):
    """Poll for an offer result generated by the LLM service via Redis."""
    if not redis_client:
        raise HttpError(503, "Offer store unavailable")
    raw = redis_client.get(f"offer:{task_id}")
    if not raw:
        return {"offer": None, "status": "pending"}
    offer = json.loads(raw)
    return {"offer": offer, "status": "ready"}


@api.post("/merchant", auth=CustomAuth())
def merchant_config(request, payload: mercSchema):
    user = request.auth
    if user.role != "merchant":
        raise HttpError(403, "Only merchants can configure offers")

    ArtemisMerchant.objects.create(
        user=user,
        max_offer=payload.max_offer,
        traffic=payload.traffic,
        target_item=payload.target_item,
    )
    dt = {
        "merchant": user.email,
        "max_offer": payload.max_offer,
        "traffic": payload.traffic,
        "target_item": payload.target_item,
    }
    result = _publish(MERCHANT_TOPIC, dt)
    return {
        "status": "published",
        "pubsub_id": str(result) if result else "local-dev",
    }
